# This file describes the keymaps that will be built by the GitHub Actions CI.

include:

  # dummy firmware, just making sure we can build for the RP2040
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: tester_pro_micro
    artifact-name: quacken_test
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DCONFIG_ZMK_STUDIO=y

  # Quacken Zero + SparkFun RP2040
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: quacken_zero
    artifact-name: quacken_zero
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DCONFIG_ZMK_STUDIO=y

  # Quacken Flex
  - board: quacken_flex
    artifact-name: quacken_flex
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DCONFIG_ZMK_STUDIO=y
